/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AlunoController;
import Controller.TurmaController;
import Model.AlunoModel;
import Model.TurmaModel;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALUNO
 */
public class BancoDeDadosDasTurmas extends javax.swing.JFrame {

    /**
     * Creates new form BancoDeDadosDasTurmas
     */
    //Conexao com o BD com o controller
    TurmaController turmasController = new TurmaController();

    public BancoDeDadosDasTurmas() {
        initComponents();
        listarTurmasComboBox();
    }

    /*
    //metodo para listar dados na tabela
    public void listarTurmasTabela(){
    List<TurmaModel> listaTurmas = controller.ListarTurmas();
    
    //criação modelo padrao de tabela
    DefaultTableModel modelo = new DefaultTableModel();
   

    for(TurmaModel t: listaTurmas){
    modelo.addRow(new Object[]{
    //ordem que está na tabela das telas.
    t.getDevolvidos(),
      t.getTurma(),  
        
       
    });
        
    }//fim do for
   
    
    }//fim do metodo de listar dados
     */
    public void listarTurmasComboBox() {
        List<TurmaModel> listaTurmas = turmasController.listarTurmas();

        //limpar a comboBox
        filtroTurma.removeAllItems();

        //jogar os dados da lista dentro da comboBox
        for (TurmaModel tu : listaTurmas) {
            filtroTurma.addItem(tu.getCodigoTurma());
        }//fim do for

    }//fim do metodo listarTurmasComboBox

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        painelPrincipalFundo = new javax.swing.JPanel();
        filtroStatus = new javax.swing.JComboBox<>();
        filtroTurma = new javax.swing.JComboBox<>();
        filtroTurnos = new javax.swing.JComboBox<>();
        botaoExportar = new javax.swing.JButton();
        cabecalhoSyncria = new javax.swing.JPanel();
        letreiroSyncria = new javax.swing.JLabel();
        iconeBibliotecaSyncria = new javax.swing.JLabel();
        iconeSair = new javax.swing.JLabel();
        iconeUsuariosBDDadosdasTurmas = new javax.swing.JLabel();
        letreiroBDdasTurmas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaBDTurmas = new javax.swing.JTable();
        botaoAdicionarAluno = new javax.swing.JButton();
        botaoAdicionarTurma = new javax.swing.JButton();
        menuDeNavegacao = new javax.swing.JMenuBar();
        guiaRegistroEmprestimo = new javax.swing.JMenu();
        guiaListaLivrosEmprestados = new javax.swing.JMenu();
        guiaCadastroLivros = new javax.swing.JMenu();
        guiaListaLivrosAcervo = new javax.swing.JMenu();
        guiaRankingLeitores = new javax.swing.JMenu();
        guiaBancoDadosTurmas = new javax.swing.JMenu();
        guiaGrafico = new javax.swing.JMenu();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco de Dados das Turmas");

        painelPrincipalFundo.setBackground(new java.awt.Color(73, 112, 138));

        filtroStatus.setBackground(new java.awt.Color(255, 255, 255));
        filtroStatus.setForeground(new java.awt.Color(0, 0, 0));
        filtroStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STATUS", "DEVOLVIDO", "NÃO DEVOLVIDO" }));
        filtroStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroStatusActionPerformed(evt);
            }
        });

        filtroTurma.setBackground(new java.awt.Color(255, 255, 255));
        filtroTurma.setForeground(new java.awt.Color(0, 0, 0));
        filtroTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURMA" }));
        filtroTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroTurmaActionPerformed(evt);
            }
        });

        filtroTurnos.setBackground(new java.awt.Color(255, 255, 255));
        filtroTurnos.setForeground(new java.awt.Color(0, 0, 0));
        filtroTurnos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TURNO", "MATUTINO", "VESPERTINO", "NOTURNO" }));
        filtroTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroTurnosActionPerformed(evt);
            }
        });

        botaoExportar.setBackground(new java.awt.Color(255, 255, 255));
        botaoExportar.setForeground(new java.awt.Color(0, 0, 0));
        botaoExportar.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\exportar.png")); // NOI18N
        botaoExportar.setText("Exportar");

        cabecalhoSyncria.setBackground(new java.awt.Color(208, 224, 235));
        cabecalhoSyncria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        letreiroSyncria.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        letreiroSyncria.setForeground(new java.awt.Color(0, 0, 0));
        letreiroSyncria.setText("Biblioteca Syncria");

        iconeBibliotecaSyncria.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro (1) (2).png")); // NOI18N

        iconeSair.setForeground(new java.awt.Color(0, 0, 0));
        iconeSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\logout_(1).png")); // NOI18N
        iconeSair.setText("Sair");
        iconeSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconeSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cabecalhoSyncriaLayout = new javax.swing.GroupLayout(cabecalhoSyncria);
        cabecalhoSyncria.setLayout(cabecalhoSyncriaLayout);
        cabecalhoSyncriaLayout.setHorizontalGroup(
            cabecalhoSyncriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecalhoSyncriaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(iconeBibliotecaSyncria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letreiroSyncria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconeSair)
                .addGap(23, 23, 23))
        );
        cabecalhoSyncriaLayout.setVerticalGroup(
            cabecalhoSyncriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(letreiroSyncria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cabecalhoSyncriaLayout.createSequentialGroup()
                .addGroup(cabecalhoSyncriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabecalhoSyncriaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(iconeBibliotecaSyncria))
                    .addGroup(cabecalhoSyncriaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(iconeSair)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        iconeUsuariosBDDadosdasTurmas.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\grupo-de-usuarios.png")); // NOI18N

        letreiroBDdasTurmas.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        letreiroBDdasTurmas.setForeground(new java.awt.Color(0, 0, 0));
        letreiroBDdasTurmas.setText("Banco de Dados das Turmas");

        tabelaBDTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Status", "Turmas", "Alunos", "Nº de Livros Retirados "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaBDTurmas);

        botaoAdicionarAluno.setBackground(new java.awt.Color(255, 255, 255));
        botaoAdicionarAluno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoAdicionarAluno.setForeground(new java.awt.Color(0, 0, 0));
        botaoAdicionarAluno.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\BibliotecaSyncria2.0\\BibliotecaSyncria2\\src\\main\\java\\Images\\Adicionar Aluno(24px).png")); // NOI18N
        botaoAdicionarAluno.setText("Adicionar Aluno");
        botaoAdicionarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarAlunoActionPerformed(evt);
            }
        });

        botaoAdicionarTurma.setBackground(new java.awt.Color(255, 255, 255));
        botaoAdicionarTurma.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botaoAdicionarTurma.setForeground(new java.awt.Color(0, 0, 0));
        botaoAdicionarTurma.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\BibliotecaSyncria2.0\\BibliotecaSyncria2\\src\\main\\java\\Images\\Adicionar Turma.png")); // NOI18N
        botaoAdicionarTurma.setText("Adicionar Turma");
        botaoAdicionarTurma.setToolTipText("");
        botaoAdicionarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarTurmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalFundoLayout = new javax.swing.GroupLayout(painelPrincipalFundo);
        painelPrincipalFundo.setLayout(painelPrincipalFundoLayout);
        painelPrincipalFundoLayout.setHorizontalGroup(
            painelPrincipalFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cabecalhoSyncria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelPrincipalFundoLayout.createSequentialGroup()
                .addGroup(painelPrincipalFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalFundoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(iconeUsuariosBDDadosdasTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(letreiroBDdasTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalFundoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1842, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(painelPrincipalFundoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(filtroTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(filtroTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(filtroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(botaoExportar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAdicionarTurma)
                .addGap(33, 33, 33)
                .addComponent(botaoAdicionarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        painelPrincipalFundoLayout.setVerticalGroup(
            painelPrincipalFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalFundoLayout.createSequentialGroup()
                .addComponent(cabecalhoSyncria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelPrincipalFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalFundoLayout.createSequentialGroup()
                        .addComponent(iconeUsuariosBDDadosdasTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalFundoLayout.createSequentialGroup()
                        .addComponent(letreiroBDdasTurmas)
                        .addGap(28, 28, 28)))
                .addGroup(painelPrincipalFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExportar)
                    .addComponent(botaoAdicionarAluno)
                    .addComponent(botaoAdicionarTurma))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        guiaRegistroEmprestimo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\registro.png")); // NOI18N
        guiaRegistroEmprestimo.setText("Registro de Empréstimo |");
        guiaRegistroEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRegistroEmprestimoMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaRegistroEmprestimo);

        guiaListaLivrosEmprestados.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro_emp._24.png")); // NOI18N
        guiaListaLivrosEmprestados.setText("Lista de Livros Emprestados |");
        guiaListaLivrosEmprestados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaListaLivrosEmprestadosMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaListaLivrosEmprestados);

        guiaCadastroLivros.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro (2).png")); // NOI18N
        guiaCadastroLivros.setText("Cadastro de Livros |");
        guiaCadastroLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaCadastroLivrosMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaCadastroLivros);

        guiaListaLivrosAcervo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\open-book.png")); // NOI18N
        guiaListaLivrosAcervo.setText("Lista de Livros no Acervo |");
        guiaListaLivrosAcervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaListaLivrosAcervoMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaListaLivrosAcervo);

        guiaRankingLeitores.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\ranking.png")); // NOI18N
        guiaRankingLeitores.setText("Ranking dos Leitores |");
        guiaRankingLeitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRankingLeitoresMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaRankingLeitores);

        guiaBancoDadosTurmas.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\grupo-de-usuarios (1).png")); // NOI18N
        guiaBancoDadosTurmas.setText("Banco de Dados das Turmas |");
        guiaBancoDadosTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaBancoDadosTurmasMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaBancoDadosTurmas);

        guiaGrafico.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\BibliotecaSyncria2.0\\BibliotecaSyncria2\\src\\main\\java\\Images\\7.Gráficos (24px).png")); // NOI18N
        guiaGrafico.setText("Gráficos");
        guiaGrafico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaGraficoMouseClicked(evt);
            }
        });
        menuDeNavegacao.add(guiaGrafico);

        setJMenuBar(menuDeNavegacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipalFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipalFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void filtroStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroStatusActionPerformed

    private void filtroTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroTurmaActionPerformed

    private void filtroTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroTurnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroTurnosActionPerformed

    private void guiaBancoDadosTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaBancoDadosTurmasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_guiaBancoDadosTurmasMouseClicked

    private void guiaRegistroEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRegistroEmprestimoMouseClicked
        // TODO add your handling code here:
        TelaRegistrosEmprestimos tela6ParaTela1 = new TelaRegistrosEmprestimos();

        //Abrindo a tela 6 para tela 1
        tela6ParaTela1.setVisible(true);

        //Fechando a tela
        dispose();
    }//GEN-LAST:event_guiaRegistroEmprestimoMouseClicked

    private void guiaListaLivrosAcervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaListaLivrosAcervoMouseClicked
        // TODO add your handling code here:

        //acesso da tela 6 para tela 4
        ListaDeLivrosNoAcervo tela6ParaTela4 = new ListaDeLivrosNoAcervo();

        //Abrindo a tela
        tela6ParaTela4.setVisible(true);

        //Fechando a tela
        dispose();
    }//GEN-LAST:event_guiaListaLivrosAcervoMouseClicked

    private void guiaRankingLeitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRankingLeitoresMouseClicked
        // TODO add your handling code here:
        TelaRankingDeLeitores tela2ParaTela5 = new TelaRankingDeLeitores();

        //Abrindo a tela 6 para tela 5
        tela2ParaTela5.setVisible(true);

        //Fechando a tela
        dispose();
    }//GEN-LAST:event_guiaRankingLeitoresMouseClicked

    private void guiaCadastroLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaCadastroLivrosMouseClicked
        // TODO add your handling code here:
        
        //acesso da Tela 6 para tela 3
        TelaDeCadastroDeLivros tela6paratela3 = new TelaDeCadastroDeLivros();

        //Abrindo a tela
        tela6paratela3.setVisible(true);

        //Fechando a tela
        dispose();
         
    }//GEN-LAST:event_guiaCadastroLivrosMouseClicked

    private void guiaListaLivrosEmprestadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaListaLivrosEmprestadosMouseClicked
        // TODO add your handling code here:

        //acesso da Tela 6 para tela 2
        ListaDeLivrosEmprestados tela6paratela2 = new ListaDeLivrosEmprestados();

        //Abrindo a tela
        tela6paratela2.setVisible(true);

        //Fechando a tela 
        dispose();
    }//GEN-LAST:event_guiaListaLivrosEmprestadosMouseClicked

    private void guiaGraficoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaGraficoMouseClicked
        // TODO add your handling code here:

        //acesso da tela 6 para tela 7
        TelaGraficos tela6ParaTela7 = new TelaGraficos();

        //Abrindo a tela
        tela6ParaTela7.setVisible(true);

        //Fechando a tela
        dispose();
    }//GEN-LAST:event_guiaGraficoMouseClicked

    private void iconeSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconeSairMouseClicked
        // TODO add your handling code here:

        //Processo de fechar o Aplicativo
        dispose();
    }//GEN-LAST:event_iconeSairMouseClicked

    private void botaoAdicionarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarAlunoActionPerformed
        // TODO add your handling code here:
            
        //JOPTIONPANE ADICIONAR ALUNO
        // Painel e fonte
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5)); // linhas dinâmicas, 2 colunas, espaçamento de 10px
        Font fonte = new Font("Segoe UI", Font.PLAIN, 16);

// Nome do aluno
        JLabel nomeLabel = new JLabel("Nome do Aluno:");
        nomeLabel.setFont(fonte);
        JTextField nomeField = new JTextField(20);
        nomeField.setFont(fonte);
        panel.add(nomeLabel);
        panel.add(nomeField);

// Matrícula
        JLabel matriculaLabel = new JLabel("Matrícula:");
        matriculaLabel.setFont(fonte);
        JTextField matriculaField = new JTextField(10);
        matriculaField.setFont(fonte);
        panel.add(matriculaLabel);
        panel.add(matriculaField);

// Turmas (carregadas do banco)
        JLabel turmaLabel = new JLabel("Turma:");
        turmaLabel.setFont(fonte);

// Buscar turmas do banco
        List<TurmaModel> listaTurmas = turmasController.listarTurmas();

// Extrair códigos para o combo
        String[] codigosTurmas = listaTurmas.stream()
                .map(TurmaModel::getCodigoTurma)
                .toArray(String[]::new);

        JComboBox<String> comboTurmas = new JComboBox<>(codigosTurmas);
        comboTurmas.setFont(fonte);

        panel.add(turmaLabel);
        panel.add(comboTurmas);

// Exibir painel em JOptionPane
        int result = JOptionPane.showConfirmDialog(null, panel, "Cadastro de Aluno",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

// Se clicou em OK
        if (result == JOptionPane.OK_OPTION) {
            try {
                String nome = nomeField.getText().trim();
                String matriculaTexto = matriculaField.getText().trim();
                int matricula = Integer.parseInt(matriculaTexto); // conversão aqui

                String codigoSelecionado = (String) comboTurmas.getSelectedItem();

                // Buscar o idTurma correspondente ao código selecionado
                int turmaIdSelecionado = 0;
                for (TurmaModel turma : listaTurmas) {
                    if (turma.getCodigoTurma().equals(codigoSelecionado)) {
                        turmaIdSelecionado = turma.getIdTurma();
                        break;
                    }
                }

                // Criar objeto Aluno com os dados
                AlunoModel aluno = new AlunoModel();
                aluno.setNome(nome);
                aluno.setMatricula(matricula); // agora é inteiro

                aluno.setTurmaId(turmaIdSelecionado);

                // Cadastrar aluno
                AlunoController controller = new AlunoController();
                boolean sucesso = controller.cadastrarAluno(aluno);

                if (sucesso) {
                    JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao cadastrar aluno.", "Erro", JOptionPane.ERROR_MESSAGE);
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "A matrícula deve ser um número inteiro.", "Erro", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro nos dados inseridos. Verifique e tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_botaoAdicionarAlunoActionPerformed

    private void botaoAdicionarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarTurmaActionPerformed
        // TODO add your handling code here:
        
         // Painel e fonte
        JPanel panelTurma = new JPanel(new GridLayout(0, 2, 5, 5));
        Font fonte = new Font("Segoe UI", Font.PLAIN, 16);

        // Código da Turma
        JLabel codigoLabel = new JLabel("Código da Turma:");
        codigoLabel.setFont(fonte);
        JTextField codigoField = new JTextField(15);
        codigoField.setFont(fonte);
        panelTurma.add(codigoLabel);
        panelTurma.add(codigoField);

        // Turno
        JLabel turnoLabel = new JLabel("Turno:");
        turnoLabel.setFont(fonte);
        String[] opcoesTurno = {"Matutino", "Vespertino", "Noturno"};
        JComboBox<String> turnoCombo = new JComboBox<>(opcoesTurno);
        turnoCombo.setFont(fonte);
        panelTurma.add(turnoLabel);
        panelTurma.add(turnoCombo);

        // Exibir painel
        int resultTurma = JOptionPane.showConfirmDialog(
            null,
            panelTurma,
            "Cadastro de Turma",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (resultTurma == JOptionPane.OK_OPTION) {
            String codigo = codigoField.getText().trim();
            String turno = (String) turnoCombo.getSelectedItem();

            // Verifica se os campos estão preenchidos
            if (codigo.isEmpty() || turno == null || turno.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.", "Campos obrigatórios", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try {
                // Criar objeto Turma
                TurmaModel novaTurma = new TurmaModel();
                novaTurma.setCodigoTurma(codigo);
                novaTurma.setTurno(turno);

                // Cadastrar turma
                TurmaController turmaController = new TurmaController();
                boolean sucesso = turmaController.cadastrarTurma(novaTurma);

                if (sucesso) {
                    JOptionPane.showMessageDialog(null, "Turma cadastrada com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao cadastrar turma", "Erro", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro nos dados inseridos. Verifique e tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }//fim do 1° if


    }//GEN-LAST:event_botaoAdicionarTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BancoDeDadosDasTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BancoDeDadosDasTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BancoDeDadosDasTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BancoDeDadosDasTurmas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BancoDeDadosDasTurmas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarAluno;
    private javax.swing.JButton botaoAdicionarTurma;
    private javax.swing.JButton botaoExportar;
    private javax.swing.JPanel cabecalhoSyncria;
    private javax.swing.JComboBox<String> filtroStatus;
    private javax.swing.JComboBox<String> filtroTurma;
    private javax.swing.JComboBox<String> filtroTurnos;
    private javax.swing.JMenu guiaBancoDadosTurmas;
    private javax.swing.JMenu guiaCadastroLivros;
    private javax.swing.JMenu guiaGrafico;
    private javax.swing.JMenu guiaListaLivrosAcervo;
    private javax.swing.JMenu guiaListaLivrosEmprestados;
    private javax.swing.JMenu guiaRankingLeitores;
    private javax.swing.JMenu guiaRegistroEmprestimo;
    private javax.swing.JLabel iconeBibliotecaSyncria;
    private javax.swing.JLabel iconeSair;
    private javax.swing.JLabel iconeUsuariosBDDadosdasTurmas;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel letreiroBDdasTurmas;
    private javax.swing.JLabel letreiroSyncria;
    private javax.swing.JMenuBar menuDeNavegacao;
    private javax.swing.JPanel painelPrincipalFundo;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTable tabelaBDTurmas;
    // End of variables declaration//GEN-END:variables
}
