/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.NovoLivroControler;
import Model.NovoLivroModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALUNO
 */
public class TelaDeCadastroDeLivros extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroLivross
     */
    NovoLivroControler controler = new NovoLivroControler();

    public TelaDeCadastroDeLivros() {
        initComponents();  
        
        listarDadosTabela();
        
    }
    
    public void listarDadosTabela(){
    
    List<NovoLivroModel> lista = controler.listarLivros();
    //criaçoa modelo padrao da tela
    DefaultTableModel modelo =  (DefaultTableModel)
          tabelaDeListaDeLivrosCadastrados.getModel();
          // limpar as linhas da tabela
          modelo.setRowCount(0);
          
          //jogar as informaçoes dentro da tabela modelo
    for(NovoLivroModel nl: lista){
       modelo.addRow(new Object[]{
       nl.getTituloObra(),
       nl.getNumeroCopias(),
       nl.getAutor()
       
       });
       
    }// fim do for
     tabelaDeListaDeLivrosCadastrados.setModel(modelo);
    
    }// FIM DO METODO DE LISTAGEM 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDoLetreiroPrincipal = new javax.swing.JPanel();
        letreiroTituloPrincipal = new java.awt.Label();
        letreiroIcone = new javax.swing.JLabel();
        painelSegundario = new javax.swing.JPanel();
        letreiroTituloSegundario = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JPanel();
        letreiroTituloObra = new java.awt.Label();
        campoDeRespostaDeTituloDaObra = new java.awt.TextField();
        letriroAutor = new java.awt.Label();
        campoDeRespostaDeAutor = new java.awt.TextField();
        letreiroAnoPublicacao = new java.awt.Label();
        letreiroEditora = new java.awt.Label();
        campoDeRespostaDeEditora = new java.awt.TextField();
        letreiroGeneroLiterario = new java.awt.Label();
        campoDeRespostaDeGeneroLiterario = new javax.swing.JComboBox<>();
        letreiroSubegenero = new java.awt.Label();
        campoDeRespostaDeSubgenero = new java.awt.TextField();
        letreiroEdicao = new java.awt.Label();
        letreiroVolume = new java.awt.Label();
        letreiroNDeCopias = new java.awt.Label();
        campoDeRespostaDeQuantidadeDeCopias = new javax.swing.JComboBox<>();
        campoDeRespoataDeEdicao = new java.awt.TextField();
        campoDeRespostaDeVolume = new java.awt.TextField();
        letreiroExemplar = new java.awt.Label();
        NDeChamada = new java.awt.Label();
        letreiroIsbn = new java.awt.Label();
        letreiroIdioma = new java.awt.Label();
        letreiroStatus = new java.awt.Label();
        letreiroLocalizacao = new java.awt.Label();
        letreiroObservacao = new java.awt.Label();
        campoDeRespostaDeExemplar = new java.awt.TextField();
        campoDeRepostaDeIsbn = new java.awt.TextField();
        campoDeRespostaDeIdioma = new java.awt.TextField();
        campoDeRespotaDeStatus = new java.awt.TextField();
        campoDeRespostaDeLocalizacao = new java.awt.TextField();
        campoDeRespotaDeObservacao = new java.awt.TextField();
        campoDeRespostaDeNumeroDeChamada = new java.awt.TextField();
        botaoSalvar = new javax.swing.JButton();
        NDeRegistros = new java.awt.Label();
        campoDeRespostaDeNRgistros = new java.awt.TextField();
        campoDeRespostaDeAnoDePublicacao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDeListaDeLivrosCadastrados = new javax.swing.JTable();
        letreiroAquisiçao = new java.awt.Label();
        campoRespostaAquisicao = new java.awt.TextField();
        letriroAnoFabricacao = new java.awt.Label();
        campoDeRespostaDeAnoFabrecacao = new java.awt.TextField();
        letreiroDatCadastro = new java.awt.Label();
        campoDeRespostaDeDataCadastro = new java.awt.TextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        guiaRegistroEmprestimo = new javax.swing.JMenu();
        guiaListaLivrosEmprestados = new javax.swing.JMenu();
        guiaCadastroLivros = new javax.swing.JMenu();
        guiaListaLivrosAcervo = new javax.swing.JMenu();
        guiaRankingLeitores = new javax.swing.JMenu();
        guiaBancoDadosTurmas = new javax.swing.JMenu();
        guiaGrafico = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelDoLetreiroPrincipal.setBackground(new java.awt.Color(208, 224, 235));
        painelDoLetreiroPrincipal.setToolTipText("");
        painelDoLetreiroPrincipal.setName(""); // NOI18N

        letreiroTituloPrincipal.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        letreiroTituloPrincipal.setText("Biblioteca Syncria");

        letreiroIcone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        letreiroIcone.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\livro (1) (2).png")); // NOI18N

        javax.swing.GroupLayout painelDoLetreiroPrincipalLayout = new javax.swing.GroupLayout(painelDoLetreiroPrincipal);
        painelDoLetreiroPrincipal.setLayout(painelDoLetreiroPrincipalLayout);
        painelDoLetreiroPrincipalLayout.setHorizontalGroup(
            painelDoLetreiroPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDoLetreiroPrincipalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(letreiroIcone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letreiroTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDoLetreiroPrincipalLayout.setVerticalGroup(
            painelDoLetreiroPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDoLetreiroPrincipalLayout.createSequentialGroup()
                .addComponent(letreiroTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(painelDoLetreiroPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(letreiroIcone, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelSegundario.setBackground(new java.awt.Color(73, 112, 138));

        letreiroTituloSegundario.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        letreiroTituloSegundario.setForeground(new java.awt.Color(0, 0, 0));
        letreiroTituloSegundario.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\BibliotecaSyncria2.0\\BibliotecaSyncria2\\src\\main\\java\\Images\\3.Cadastro de Livros (64px).png")); // NOI18N
        letreiroTituloSegundario.setText("Cadastro de Livros");

        painelPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        letreiroTituloObra.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroTituloObra.setText("Título da Obra: ");

        campoDeRespostaDeTituloDaObra.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        letriroAutor.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letriroAutor.setText("Autor(a):");

        campoDeRespostaDeAutor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        letreiroAnoPublicacao.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroAnoPublicacao.setText("Ano de Publicação: ");

        letreiroEditora.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroEditora.setText("Editora: ");

        campoDeRespostaDeEditora.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        letreiroGeneroLiterario.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroGeneroLiterario.setText("Gênero Literário:");

        campoDeRespostaDeGeneroLiterario.setBackground(new java.awt.Color(255, 255, 255));
        campoDeRespostaDeGeneroLiterario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoDeRespostaDeGeneroLiterario.setForeground(new java.awt.Color(0, 0, 0));
        campoDeRespostaDeGeneroLiterario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Aventura", "Autobiografia", "Biografia", "Chick Lit", "Comédia", "Conto", "Crônica", "Cyberpunk", "Dark Fantasy", "Distopia", "Drama", "Ensaio", "Épico", "Fábula", "Fantasia", "Fantasia Urbana", "Ficção Científica", "Ficção Filosófica", "Ficção Histórica", "Ficção Policial", "Ficção Psicológica", "High Fantasy", "Literatura Afro-brasileira", "Literatura Científica", "Literatura Clássica", "Literatura de Autoajuda", "Literatura de Cordel", "Literatura de Horror Cósmico", "Literatura de Viagem", "Literatura Espírita", "Literatura Espiritualista", "Literatura Erótica", "Literatura Feminina", "Literatura Gótica", "Literatura Infantil", "Literatura Juvenil", "Literatura LGBTQIA+", "Literatura Regionalista", "Literatura Religiosa", "Literatura Técnica", "Low Fantasy", "Magical Realism (Realismo Fantástico)", "Memórias", "Mistério", "Modernismo", "Naturalismo", "New Adult (NA)", "Novela", "Parábola", "Poesia", "Pós-modernismo", "Realismo", "Romance", "Romance Contemporâneo", "Romance de Época", "Romance de Ficção Científica", "Romance de Formação (Bildungsroman)", "Romance Distópico", "Romance Gótico", "Romance Histórico", "Romance Policial", "Romance Psicológico", "Sátira", "Space Opera", "Steampunk", "Suspense", "Sword and Sorcery", "Terror", "Tragédia", "Utopia", "Young Adult (YA)", " " }));

        letreiroSubegenero.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroSubegenero.setText("Subgênero: ");

        campoDeRespostaDeSubgenero.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        letreiroEdicao.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroEdicao.setText("Edição:");

        letreiroVolume.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroVolume.setText("Volume:");

        letreiroNDeCopias.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroNDeCopias.setText("Nº de Cópias:");

        campoDeRespostaDeQuantidadeDeCopias.setBackground(new java.awt.Color(255, 255, 255));
        campoDeRespostaDeQuantidadeDeCopias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoDeRespostaDeQuantidadeDeCopias.setForeground(new java.awt.Color(0, 0, 0));
        campoDeRespostaDeQuantidadeDeCopias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "171", "172", "173", "174", "175", "176", "177", "178", "179", "180", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "211", "212", "213", "214", "215", "216", "217", "218", "219", "220", "221", "222", "223", "224", "225", "226", "227", "228", "229", "230", "231", "232", "233", "234", "235", "236", "237", "238", "239", "240", "241", "242", "243", "244", "245", "246", "247", "248", "249", "250", "251", "252", "253", "254", "255", "256", "257", "258", "259", "260", "261", "262", "263", "264", "265", "266", "267", "268", "269", "270", "271", "272", "273", "274", "275", "276", "277", "278", "279", "280", "281", "282", "283", "284", "285", "286", "287", "288", "289", "290", "291", "292", "293", "294", "295", "296", "297", "298", "299", "300", "301", "302", "303", "304", "305", "306", "307", "308", "309", "310", "311", "312", "313", "314", "315", "316", "317", "318", "319", "320", "321", "322", "323", "324", "325", "326", "327", "328", "329", "330", "331", "332", "333", "334", "335", "336", "337", "338", "339", "340", "341", "342", "343", "344", "345", "346", "347", "348", "349", "350", " " }));
        campoDeRespostaDeQuantidadeDeCopias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeRespostaDeQuantidadeDeCopiasActionPerformed(evt);
            }
        });

        campoDeRespoataDeEdicao.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        campoDeRespoataDeEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeRespoataDeEdicaoActionPerformed(evt);
            }
        });

        campoDeRespostaDeVolume.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        letreiroExemplar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroExemplar.setText("Exemplar ");

        NDeChamada.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NDeChamada.setText("Nº de Chamada");

        letreiroIsbn.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroIsbn.setText("ISBN:");

        letreiroIdioma.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroIdioma.setText("Idioma:");

        letreiroStatus.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroStatus.setText("Status:");

        letreiroLocalizacao.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroLocalizacao.setText("Localização:");

        letreiroObservacao.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroObservacao.setText("Observações:");

        campoDeRespostaDeExemplar.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        campoDeRespostaDeExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeRespostaDeExemplarActionPerformed(evt);
            }
        });

        campoDeRepostaDeIsbn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        campoDeRespostaDeIdioma.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        campoDeRespotaDeStatus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoDeRespotaDeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeRespotaDeStatusActionPerformed(evt);
            }
        });

        campoDeRespostaDeLocalizacao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        campoDeRespotaDeObservacao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        campoDeRespostaDeNumeroDeChamada.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        botaoSalvar.setBackground(new java.awt.Color(51, 255, 0));
        botaoSalvar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        botaoSalvar.setForeground(new java.awt.Color(0, 0, 0));
        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        NDeRegistros.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        NDeRegistros.setText("N°Registro");

        campoDeRespostaDeNRgistros.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        campoDeRespostaDeAnoDePublicacao.setBackground(new java.awt.Color(255, 255, 255));
        campoDeRespostaDeAnoDePublicacao.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        campoDeRespostaDeAnoDePublicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeRespostaDeAnoDePublicacaoActionPerformed(evt);
            }
        });

        tabelaDeListaDeLivrosCadastrados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabelaDeListaDeLivrosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo da Obra", "N° de Copias", "Autor (a)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaDeListaDeLivrosCadastrados);

        letreiroAquisiçao.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroAquisiçao.setText("Aquisição:");

        campoRespostaAquisicao.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        letriroAnoFabricacao.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letriroAnoFabricacao.setText("Ano de Fabricação:");

        campoDeRespostaDeAnoFabrecacao.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        letreiroDatCadastro.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        letreiroDatCadastro.setText("Data de Cadastro:");

        campoDeRespostaDeDataCadastro.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        campoDeRespostaDeDataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeRespostaDeDataCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(letriroAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDeRespostaDeAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(letreiroIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(campoDeRepostaDeIsbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(letreiroIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDeRespostaDeIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(letreiroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(campoDeRespotaDeStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addComponent(letreiroLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoDeRespostaDeLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(letreiroTituloObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(campoDeRespostaDeTituloDaObra, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letreiroNDeCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDeRespostaDeQuantidadeDeCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(letreiroExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDeRespostaDeExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPrincipalLayout.createSequentialGroup()
                                .addComponent(NDeRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDeRespostaDeNRgistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(campoDeRespostaDeVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPrincipalLayout.createSequentialGroup()
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letreiroVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(letreiroEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(campoDeRespoataDeEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPrincipalLayout.createSequentialGroup()
                                .addComponent(letreiroGeneroLiterario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(campoDeRespostaDeGeneroLiterario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPrincipalLayout.createSequentialGroup()
                                .addComponent(letreiroEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(campoDeRespostaDeEditora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPrincipalLayout.createSequentialGroup()
                                .addComponent(letreiroAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDeRespostaDeAnoDePublicacao))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPrincipalLayout.createSequentialGroup()
                                .addComponent(letreiroSubegenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(campoDeRespostaDeSubgenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelPrincipalLayout.createSequentialGroup()
                                .addComponent(NDeChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(campoDeRespostaDeNumeroDeChamada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                                        .addComponent(letreiroAquisiçao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoRespostaAquisicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(letreiroObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoDeRespotaDeObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                                        .addComponent(letreiroDatCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(campoDeRespostaDeDataCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                                        .addComponent(letriroAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(campoDeRespostaDeAnoFabrecacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)))))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(letreiroNDeCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(letreiroTituloObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoDeRespostaDeTituloDaObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(campoDeRespostaDeQuantidadeDeCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letreiroIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(campoDeRepostaDeIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(letriroAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoDeRespostaDeAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(letreiroIdioma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoDeRespostaDeIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(letreiroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDeRespotaDeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(letreiroAnoPublicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoDeRespostaDeAnoDePublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(20, 20, 20)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(campoDeRespostaDeNumeroDeChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NDeRegistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDeRespostaDeNRgistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(274, 274, 274))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letreiroEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDeRespostaDeEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(letreiroLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDeRespostaDeLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(letreiroGeneroLiterario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoDeRespostaDeGeneroLiterario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoDeRespostaDeSubgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(letreiroSubegenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19)
                                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(letreiroEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoDeRespoataDeEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(campoDeRespostaDeVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(letreiroVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(19, 19, 19)
                                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(letreiroExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoDeRespostaDeExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addComponent(NDeChamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(325, 325, 325))
                                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(campoDeRespostaDeAnoFabrecacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(letriroAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(letreiroDatCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoDeRespostaDeDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoDeRespotaDeObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(letreiroObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(painelPrincipalLayout.createSequentialGroup()
                                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(letreiroAquisiçao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoRespostaAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelSegundarioLayout = new javax.swing.GroupLayout(painelSegundario);
        painelSegundario.setLayout(painelSegundarioLayout);
        painelSegundarioLayout.setHorizontalGroup(
            painelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSegundarioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(letreiroTituloSegundario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(painelSegundarioLayout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        painelSegundarioLayout.setVerticalGroup(
            painelSegundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSegundarioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(letreiroTituloSegundario)
                .addGap(18, 18, 18)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        guiaRegistroEmprestimo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\BibliotecaSyncria2.0\\BibliotecaSyncria2\\src\\main\\java\\Images\\1.Registro de Emprestimos (24px).png")); // NOI18N
        guiaRegistroEmprestimo.setText("Registro de Empréstimo |");
        guiaRegistroEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRegistroEmprestimoMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaRegistroEmprestimo);

        guiaListaLivrosEmprestados.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\BibliotecaSyncria2.0\\BibliotecaSyncria2\\src\\main\\java\\Images\\2.Lista de Livros Emprestados (24px).png")); // NOI18N
        guiaListaLivrosEmprestados.setText("Lista de Livros Emprestados |");
        guiaListaLivrosEmprestados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaListaLivrosEmprestadosMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaListaLivrosEmprestados);

        guiaCadastroLivros.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\BibliotecaSyncria2.0\\BibliotecaSyncria2\\src\\main\\java\\Images\\3.Cadastro de Livros (24px).png")); // NOI18N
        guiaCadastroLivros.setText("Cadastro de Livros |");
        guiaCadastroLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaCadastroLivrosMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaCadastroLivros);

        guiaListaLivrosAcervo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\BibliotecaSyncria2.0\\BibliotecaSyncria2\\src\\main\\java\\Images\\4.Lista de Livros no Acervo (24px).png")); // NOI18N
        guiaListaLivrosAcervo.setText("Lista de Livros no Acervo |");
        guiaListaLivrosAcervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaListaLivrosAcervoMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaListaLivrosAcervo);

        guiaRankingLeitores.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\BibliotecaSyncria2.0\\BibliotecaSyncria2\\src\\main\\java\\Images\\5.Ranking dos Leitores (24px).png")); // NOI18N
        guiaRankingLeitores.setText("Ranking dos Leitores |");
        guiaRankingLeitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaRankingLeitoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaRankingLeitores);

        guiaBancoDadosTurmas.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\BibliotecaSyncria2.0\\BibliotecaSyncria2\\src\\main\\java\\Images\\6.Banco de Dados das Turmas (24px).png")); // NOI18N
        guiaBancoDadosTurmas.setText("Banco de Dados das Turmas |");
        guiaBancoDadosTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaBancoDadosTurmasMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaBancoDadosTurmas);

        guiaGrafico.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Documents\\NetBeansProjects\\BibliotecaSyncria2.0\\BibliotecaSyncria2\\src\\main\\java\\Images\\7.Gráficos (24px).png")); // NOI18N
        guiaGrafico.setText("Grafico");
        guiaGrafico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guiaGraficoMouseClicked(evt);
            }
        });
        jMenuBar1.add(guiaGrafico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelDoLetreiroPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelSegundario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelDoLetreiroPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelSegundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoDeRespostaDeQuantidadeDeCopiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeRespostaDeQuantidadeDeCopiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeRespostaDeQuantidadeDeCopiasActionPerformed

    private void campoDeRespoataDeEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeRespoataDeEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeRespoataDeEdicaoActionPerformed

    private void campoDeRespostaDeExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeRespostaDeExemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeRespostaDeExemplarActionPerformed

    private void campoDeRespotaDeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeRespotaDeStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeRespotaDeStatusActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
       try {
        NovoLivroModel livro = new NovoLivroModel();

        livro.setTituloObra(campoDeRespostaDeTituloDaObra.getText());
        livro.setNumeroCopias(Integer.parseInt(campoDeRespostaDeQuantidadeDeCopias.getSelectedItem().toString()));
        livro.setDataCadastro(campoDeRespostaDeDataCadastro.getText());
        livro.setGenerosLiterarios(campoDeRespostaDeGeneroLiterario.getSelectedItem().toString());
        livro.setSubgenerosLiterarios(campoDeRespostaDeSubgenero.getText());
        livro.setAutor(campoDeRespostaDeAutor.getText());
        livro.setNumeroRegistro(Integer.parseInt(campoDeRespostaDeNRgistros.getText()));
        livro.setEdicao(campoDeRespoataDeEdicao.getText());
        livro.setVolume(campoDeRespostaDeVolume.getText());
        livro.setLocalizacao(campoDeRespostaDeLocalizacao.getText());
        livro.setEditora(campoDeRespostaDeEditora.getText());
        livro.setAnoFabricacao(Integer.parseInt(campoDeRespostaDeAnoFabrecacao.getText()));
        livro.setAnoPublicacao(Integer.parseInt(campoDeRespostaDeAnoDePublicacao.getText()));
        livro.setAquisicao(campoRespostaAquisicao.getText());
        livro.setExemplar(campoDeRespostaDeExemplar.getText());
        livro.setNumeroChamada(campoDeRespostaDeNumeroDeChamada.getText());
        livro.setIsbn(campoDeRepostaDeIsbn.getText());
        livro.setStatusLivros(campoDeRespotaDeStatus.getText());
        livro.setObservacoes(campoDeRespotaDeObservacao.getText());
        livro.setQuantidadeTituloEmprestado(0); // Padrão zero no cadastro
        livro.setQuantidadeTituloAcervo(Integer.parseInt(campoDeRespostaDeQuantidadeDeCopias.getSelectedItem().toString()));

        // Chamada ao DAO
        
        controler.inserirLivro(livro);

        JOptionPane.showMessageDialog(this, "Livro cadastrado com sucesso!");

       

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao cadastrar livro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
       
        listarDadosTabela();
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void campoDeRespostaDeAnoDePublicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeRespostaDeAnoDePublicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeRespostaDeAnoDePublicacaoActionPerformed

    private void campoDeRespostaDeDataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeRespostaDeDataCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeRespostaDeDataCadastroActionPerformed

    private void guiaGraficoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaGraficoMouseClicked
        // TODO add your handling code here:
        TelaGraficos grafico =new TelaGraficos();
        grafico.setVisible(true);
        // fechar tela de login
                    dispose();
            ;
    }//GEN-LAST:event_guiaGraficoMouseClicked

    private void guiaBancoDadosTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaBancoDadosTurmasMouseClicked
        // TODO add your handling code here:
        //criar objeto da classe 
        BancoDeDadosDasTurmas bancoDadosTurma = new BancoDeDadosDasTurmas();
               // abrindo a tela
                bancoDadosTurma.setVisible(true);
        // fechar tela de login
                    dispose();
            ;
    }//GEN-LAST:event_guiaBancoDadosTurmasMouseClicked

    private void guiaRankingLeitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRankingLeitoresMouseClicked
        // TODO add your handling code here:
       TelaRankingDeLeitores rankisngDosLeitores = new TelaRankingDeLeitores (); 
               rankisngDosLeitores.setVisible(true);
        // fechar tela de login
                    dispose();
            
    }//GEN-LAST:event_guiaRankingLeitoresMouseClicked

    private void guiaListaLivrosAcervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaListaLivrosAcervoMouseClicked
        // TODO add your handling code here:
           
        //criar objeto da classe 
        ListaDeLivrosNoAcervo livrosAcervo = new ListaDeLivrosNoAcervo();
               // abrindo a tela
                livrosAcervo.setVisible(true);
        // fechar tela de login
                    dispose();
           
    }//GEN-LAST:event_guiaListaLivrosAcervoMouseClicked

    private void guiaCadastroLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaCadastroLivrosMouseClicked
        // TODO add your handling code here:  
     
    }//GEN-LAST:event_guiaCadastroLivrosMouseClicked

    private void guiaListaLivrosEmprestadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaListaLivrosEmprestadosMouseClicked
        // TODO add your handling code here:   
       //criar objeto da classe 
        ListaDeLivrosEmprestados listaEmprestado = new ListaDeLivrosEmprestados();
               // abrindo a tela
                listaEmprestado.setVisible(true);
        // fechar tela de login
                    dispose();
            
    }//GEN-LAST:event_guiaListaLivrosEmprestadosMouseClicked

    private void guiaRegistroEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guiaRegistroEmprestimoMouseClicked
        // TODO add your handling code here:
             //criar objeto da classe 
        TelaRegistrosEmprestimos registroEmprestimo = new TelaRegistrosEmprestimos();
               // abrindo a tela
                registroEmprestimo.setVisible(true);
        // fechar tela de login
                    dispose();
            
        
    }//GEN-LAST:event_guiaRegistroEmprestimoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastroDeLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastroDeLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastroDeLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeCadastroDeLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeCadastroDeLivros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label NDeChamada;
    private java.awt.Label NDeRegistros;
    private javax.swing.JButton botaoSalvar;
    private java.awt.TextField campoDeRepostaDeIsbn;
    private java.awt.TextField campoDeRespoataDeEdicao;
    private javax.swing.JTextField campoDeRespostaDeAnoDePublicacao;
    private java.awt.TextField campoDeRespostaDeAnoFabrecacao;
    private java.awt.TextField campoDeRespostaDeAutor;
    private java.awt.TextField campoDeRespostaDeDataCadastro;
    private java.awt.TextField campoDeRespostaDeEditora;
    private java.awt.TextField campoDeRespostaDeExemplar;
    private javax.swing.JComboBox<String> campoDeRespostaDeGeneroLiterario;
    private java.awt.TextField campoDeRespostaDeIdioma;
    private java.awt.TextField campoDeRespostaDeLocalizacao;
    private java.awt.TextField campoDeRespostaDeNRgistros;
    private java.awt.TextField campoDeRespostaDeNumeroDeChamada;
    private javax.swing.JComboBox<String> campoDeRespostaDeQuantidadeDeCopias;
    private java.awt.TextField campoDeRespostaDeSubgenero;
    private java.awt.TextField campoDeRespostaDeTituloDaObra;
    private java.awt.TextField campoDeRespostaDeVolume;
    private java.awt.TextField campoDeRespotaDeObservacao;
    private java.awt.TextField campoDeRespotaDeStatus;
    private java.awt.TextField campoRespostaAquisicao;
    private javax.swing.JMenu guiaBancoDadosTurmas;
    private javax.swing.JMenu guiaCadastroLivros;
    private javax.swing.JMenu guiaGrafico;
    private javax.swing.JMenu guiaListaLivrosAcervo;
    private javax.swing.JMenu guiaListaLivrosEmprestados;
    private javax.swing.JMenu guiaRankingLeitores;
    private javax.swing.JMenu guiaRegistroEmprestimo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label letreiroAnoPublicacao;
    private java.awt.Label letreiroAquisiçao;
    private java.awt.Label letreiroDatCadastro;
    private java.awt.Label letreiroEdicao;
    private java.awt.Label letreiroEditora;
    private java.awt.Label letreiroExemplar;
    private java.awt.Label letreiroGeneroLiterario;
    private javax.swing.JLabel letreiroIcone;
    private java.awt.Label letreiroIdioma;
    private java.awt.Label letreiroIsbn;
    private java.awt.Label letreiroLocalizacao;
    private java.awt.Label letreiroNDeCopias;
    private java.awt.Label letreiroObservacao;
    private java.awt.Label letreiroStatus;
    private java.awt.Label letreiroSubegenero;
    private java.awt.Label letreiroTituloObra;
    private java.awt.Label letreiroTituloPrincipal;
    private javax.swing.JLabel letreiroTituloSegundario;
    private java.awt.Label letreiroVolume;
    private java.awt.Label letriroAnoFabricacao;
    private java.awt.Label letriroAutor;
    private javax.swing.JPanel painelDoLetreiroPrincipal;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelSegundario;
    private javax.swing.JTable tabelaDeListaDeLivrosCadastrados;
    // End of variables declaration//GEN-END:variables

   
       
    
}
